apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountapi
  labels:
    name: accountapi
    app: accountapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: accountapi-app-pod
      app: accountapi-app
  template:
    metadata:
      name: accountapi-app-pod
      labels:
        name: accountapi-app-pod
        app: accountapi-app
    spec:
      containers:
        - name: accountapi-app
          image: bstraehle/accountapi:1.0.0
          ports:
            - containerPort: 80