apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountapi
  labels:
    name: account-api
    app: account-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: account-api-app-pod
      app: account-api-app
  template:
    metadata:
      name: account-api-app-pod
      labels:
        name: account-api-app-pod
        app: account-api-app
    spec:
      containers:
        - name: account-api-app
          image: bstraehle/account-api:1.0.0
          ports:
            - containerPort: 80
