apiVersion: v1
kind: Service
metadata:
  name: account-api-service
  labels:
    name: account-api-service
    app: account-api-app
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 80
  selector:
    name: account-api-app-pod
    app: account-api-app
