apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactapi
  labels:
    name: contactapi
    app: contactapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: contactapi-app-pod
      app: contactapi-app
  template:
    metadata:
      name: contactapi-app-pod
      labels:
        name: contactapi-app-pod
        app: contactapi-app
    spec:
      containers:
        - name: contactapi-app
          image: bstraehle/contactapi:1.0.0
          ports:
            - containerPort: 80