apiVersion: v1
kind: Service
metadata:
  name: contact-api-service
  labels:
    name: contact-api-service
    app: contact-api-app
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 80
  selector:
    name: contact-api-app-pod
    app: contact-api-app
