apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api
  labels:
    name: contact-api
    app: contact-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: contact-api-app-pod
      app: contact-api-app
  template:
    metadata:
      name: contact-api-app-pod
      labels:
        name: contact-api-app-pod
        app: contact-api-app
    spec:
      containers:
        - name: contact-api-app
          image: bstraehle/contact-api:1.0.0
          ports:
            - containerPort: 80
