apiVersion: v1
kind: Service
metadata:
  name: mvc-app-service
  labels:
    name: mvc-app-service
    app: mvc-app-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
  selector:
    name: mvc-app-app-pod
    app: mvc-app-app
