apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-app
  labels:
    name: mvc-app
    app: mvc-app-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mvc-app-app-pod
      app: mvc-app-app
  template:
    metadata:
      name: mvc-app-app-pod
      labels:
        name: mvc-app-app-pod
        app: mvc-app-app
    spec:
      containers:
        - name: mvc-app-app
          image: bstraehle/mvc-app:latest
        - env:
          - name: DEMO_API_HOST
            value: "http://rest-api-service.default.svc.cluster.local:8001"
          ports:
            - containerPort: 80
