apiVersion: v1
kind: Service
metadata:
  name: mvcclient-service
  labels:
    name: mvcclient-service
    app: mvcclient-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
  selector:
    name: mvcclient-app-pod
    app: mvcclient-app