apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  labels:
    name: rest-api-service
    app: rest-api-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 80
  selector:
    name: rest-api-app-pod
    app: rest-api-app
