apiVersion: v1
kind: Service
metadata:
  name: spa-app-service
  labels:
    name: spa-app-service
    app: spa-app-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
  selector:
    name: spa-app-app-pod
    app: spa-app-app
