apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-app
  labels:
    name: spa-app
    app: spa-app-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spa-app-app-pod
      app: spa-app-app
  template:
    metadata:
      name: spa-app-app-pod
      labels:
        name: spa-app-app-pod
        app: spa-app-app
    spec:
      containers:
        - name: spa-app-app
          image: bstraehle/spa-app:1.0.0
          ports:
            - containerPort: 80
